// Generated by js_of_ocaml 2.8.2
(function(q){"use strict";var
M="Sys_error",Y=224,X="Invalid_argument",l=1024,L=57343,W=512,V="End_of_file",U="Failure",K="Undefined_recursive_module",T="Stack_overflow",d=128,b="",u=" : file already exists",H=2048,I=56320,J=240,c=248,S="Not_found",F="Assert_failure",G="/",Q="Sys_blocked_io",R="fd ",E="Out_of_memory",P="Match_failure",O="Division_by_zero",N=1e3,av=0;function
m(){return av++}function
aa(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aF(g){for(var
h=b,c=h,a,j,e=0,i=g.length;e<i;e++){a=g.charCodeAt(e);if(a<d){for(var
f=e+1;f<i&&(a=g.charCodeAt(f))<d;f++);if(f-e>W){c.substr(0,1);h+=c;c=b;h+=g.slice(e,f)}else
c+=g.slice(e,f);if(f==i)break;e=f}if(a<H){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(d|a&63)}else
if(a<55296||a>=L)c+=String.fromCharCode(Y|a>>12,d|a>>6&63,d|a&63);else
if(a>=56319||e+1==i||(j=g.charCodeAt(e+1))<I||j>L)c+="\xef\xbf\xbd";else{e++;a=(a<<10)+j-56613888;c+=String.fromCharCode(J|a>>18,d|a>>12&63,d|a>>6&63,d|a&63)}if(c.length>l){c.substr(0,1);h+=c;c=b}}return h+c}function
az(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aI(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
x(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=l,a-=l)f+=e.apply(null,aI(c,d,Math.min(a,l)));return f}function
_(a){if(a.t==2)a.c+=az(a.l-a.c.length,"\0");else
a.c=x(a.c,0,a.c.length);a.t=0}function
aE(g){for(var
m=b,e=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<d){for(var
f=c+1;f<k&&(h=g.charCodeAt(f))<d;f++);if(f-c>W){e.substr(0,1);m+=e;e=b;m+=g.slice(c,f)}else
e+=g.slice(c,f);if(f==k)break;c=f}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==d){i=j+(h<<6);if(h<Y){a=i-12416;if(a<d)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==d){i=j+(i<<6);if(h<J){a=i-925824;if(a<H||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==d&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;e+="\ufffd"}else
if(a>65535)e+=String.fromCharCode(55232+(a>>10),I+(a&1023));else
e+=String.fromCharCode(a);if(e.length>l){e.substr(0,1);m+=e;e=b}}return m+e}function
aD(a){switch(a.t){case
9:return a.c;default:_(a);case
0:if(aa(a.c)){a.t=9;return a.c}a.t=8;case
8:return aE(a.c)}}function
h(c,a,b){this.t=c;this.c=a;this.l=b}h.prototype.toString=function(){return aD(this)};function
ab(a){var
b=9;if(!aa(a))b=8,a=aF(a);return new
h(b,a,a.length)}function
aw(b,a){throw[0,b,a]}function
a(a){return new
h(0,a,a.length)}function
af(c,b){aw(c,a(b))}var
e=[0];function
g(a){af(e.Sys_error,a)}function
ac(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==b)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=b;return 0}function
$(a){af(e.Invalid_argument,a)}function
k(a){if(a<0)$("String.create");return new
h(a?2:9,b,a)}var
ag=0;function
aJ(){return new
Date().getTime()/N}function
y(){return Math.floor(aJ())}function
i(b){this.data=b;this.inode=ag++;var
a=y();this.atime=a;this.mtime=a;this.ctime=a}i.prototype={truncate:function(){this.data=k(0);this.modified()},modified:function(){var
a=y();this.atime=a;this.mtime=a}};function
o(a){return a.l}function
ae(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
ao=G;function
r(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=ao+a;var
e=a.split(G),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
j(){this.content={};this.inode=ag++;var
a=y();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(b,a){this.content[b]=a},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
s=new
j();s.mk(b,new
j());function
w(c){var
a=s;for(var
b=0;b<c.length;b++){if(!(a.exists&&a.exists(c[b])))ae(c.orig);a=a.get(c[b])}return a}function
aC(b){var
c=r(b),a=w(c);return a
instanceof
j?1:0}function
aA(a){return new
h(4,a,a.length)}function
Z(b){if(q.Uint8Array)var
c=new(q.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
aK(a){if(a.t!=4)Z(a);return a.c}function
ap(l,c){var
e=r(l),b=s;for(var
f=0;f<e.length-1;f++){var
d=e[f];if(!b.exists(d))b.mk(d,new
j());b=b.get(d);if(!(b
instanceof
j))g(e.orig+u)}var
d=e[e.length-1];if(b.exists(d))g(e.orig+u);if(c
instanceof
j)b.mk(d,c);else
if(c
instanceof
i)b.mk(d,c);else
if(c
instanceof
h)b.mk(d,new
i(c));else
if(c
instanceof
Array)b.mk(d,new
i(aA(c)));else
if(c.toString){var
k=a(c.toString());b.mk(d,new
i(k))}else
$("caml_fs_register");return 0}function
aB(f){var
a=s,c=r(f),d,e;for(var
b=0;b<c.length;b++){if(a.auto){d=a.auto;e=b}if(!(a.exists&&a.exists(c[b])))return d?d(c,e):0;a=a.get(c[b])}return 1}function
p(c,d,a){if(e.fds===undefined)e.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?o(d.data):0;b.flags=a;e.fds[c]=b;e.fd_last_idx=c;return c}function
aL(b,d,j){var
a={};while(d){switch(d[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}d=d[2]}var
f=b.toString(),i=r(b);if(a.rdonly&&a.wronly)g(f+" : flags Open_rdonly and Open_wronly are not compatible");if(a.text&&a.binary)g(f+" : flags Open_text and Open_binary are not compatible");if(aB(b)){if(aC(b))g(f+" : is a directory");if(a.create&&a.excl)g(f+u);var
h=e.fd_last_idx?e.fd_last_idx:0,c=w(i);if(a.truncate)c.truncate();return p(h+1,c,a)}else
if(a.create){var
h=e.fd_last_idx?e.fd_last_idx:0;ap(b,k(0));var
c=w(i);return p(h+1,c,a)}else
ae(b)}p(0,new
i(k(0)));p(1,new
i(k(0)));p(2,new
i(k(0)));function
aq(b){var
a=e.fds[b];if(a.flags.wronly)g(R+b+" is writeonly");return{file:a.file,offset:a.offset,fd:b,opened:true,refill:null}}function
v(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?x(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?x(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)Z(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aG(a){var
b=q;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aH(a){var
b=q;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}var
n=new
Array();function
ay(b,h){var
g=a(h),c=o(g),f=o(b.file.data),e=b.offset;if(e+c>=f){var
d=k(e+c);v(b.file.data,0,d,0,f);v(g,0,d,e,c);b.file.data=d}b.offset+=c;b.file.modified();return 0}function
ad(a){var
c;switch(a){case
1:c=aH;break;case
2:c=aG;break;default:c=ay}var
f=e.fds[a];if(f.flags.rdonly)g(R+a+" is readonly");var
d={file:f.file,offset:f.offset,fd:a,opened:true,buffer:b,output:c};n[d.fd]=d;return d}function
ar(){var
b=0;for(var
a=0;a<n.length;a++)if(n[a]&&n[a].opened)b=[0,n[a],b];return b}function
as(a,d,h,f){if(!a.opened)g("Cannot output to a closed channel");var
c;if(h==0&&o(d)==f)c=d;else{c=k(f);v(d,h,c,0,f)}var
b=c.toString(),e=b.lastIndexOf("\n");if(e<0)a.buffer+=b;else{a.buffer+=b.substr(0,e+1);ac(a);a.buffer+=b.substr(e+1)}return 0}function
au(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:N}function
f(c,b,a){e[c+1]=b;if(a)e[a]=b}var
at={};function
an(a){if((a.t&6)!=0)_(a);return a.c}function
ax(a,b){at[an(a)]=b;return 0}f(11,[c,a(K),-12],K);f(10,[c,a(F),-11],F);f(9,[c,a(Q),-10],Q);f(8,[c,a(T),-9],T);f(7,[c,a(P),-8],P);f(6,[c,a(S),-7],S);f(5,[c,a(O),-6],O);f(4,[c,a(V),-5],V);f(3,[c,a(X),-4],X);f(2,[c,a(U),-3],U);f(1,[c,a(M),-2],M);f(0,[c,a(E),-1],E);m(0);aq(0);var
z=ad(1);ad(2);var
ak=a("Js.Error"),am=a("hello world");function
A(b,a){return as(b,a,0,o(a))}m(0);m(0);m(0);var
B=[0,0];function
C(a){B[1]=[0,a,B[1]];return 0}var
aj=q.Array,D=[c,ak,m(0)],t=[0,D,{}],ai=au(t)===c?t:t[1];ax(a("jsError"),ai);(function(a){throw a});C(function(a){return a[1]===D?[0,ab(a[2].toString())]:0});C(function(a){return a
instanceof
aj?0:[0,ab(a.toString())]});function
al(b,a){debugger;0;return b+a|0}A(z,am);A(z,a(b+al(1,2)));function
ah(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{ac(d)}catch(a){}var
a=c;continue}return 0}}ah(ar(0));return}(function(){return this}()));

//# sourceMappingURL=debug.map